name: Run Postman Automated Booking API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ensure Node.js is installed

    # Step 3: Install Newman
    - name: Install Newman
      run: npm install -g newman

    # Step 4: Run the Postman collection with environment, globals, and generate HTML report
    - name: Run Postman Collection
      run: |
        newman run MyCollection.json \
          --environment MyEnvironment.json \
          --globals MyGlobals.json \
          --reporters cli,html \
          --reporter-html-export report/report.html

    # Step 5: Upload HTML report as an artifact
    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: report/report.html
