name: Run Postman Automated Booking API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Ensure Node.js is installed

    # Step 3: Install Newman
    - name: Install Newman
      run: npm install -g newman

    # Step 4: Install Newman HTML Reporter
    - name: Install Newman HTML Reporter
      run: npm install -g newman-reporter-htmlextra
   
    # Step 5: Run the Postman collection with environment, globals, and generate HTML report
    - name: Run Postman Collection
      run: |
        newman run postman/BookingAPIsCollection.json --environment postman/BookingAPIsEnvironmentVariables.json --globals postman/BookingAPIsGlobals.json -r htmlextra --reporter-htmlextra-export newman/report.html

    # Step 6: Upload HTML report as an artifact
    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: newman/report.html

    # Step 7: Sending email with report attachment
    - name: Send email with HTML report
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Test Results for Build #${{ github.run_number }} - ${{ github.repository }} for POSTMAN API Automation"
          html_body: file://newman/report.html
          # body: |
          #     This Test case results ran after executing
          #     all postman Booking API collections for all HTTP Request Methods. Please find the attached report.
          to: niyazhashmi161921@gmail.com
          from: niyazhashmi161921@gmail.com
          attachments: newman/report.html
          secure: true